apiVersion: apps/v1
kind: Deployment

metadata:
  name: gallery-service

spec:
  replicas: 1

  selector:
    matchLabels: 
      app: gallery-service

  template:
    metadata:
      labels:
        app: gallery-service

    spec:
      containers:
      - name: gallery-service
        image: gallery-service:v1
        imagePullPolicy: Never

        ports:
        - containerPort: 3002

