apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-payment-pvc
  labels:
    app: mysql-payment
    owner: roihan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
