apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
    owner: roihan
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
    - port: 3004
      targetPort: 3004
