# ============================================
# Kubernetes Deployment - Frontend Service
# ============================================
# File ini menjalankan pod frontend-service yang menyajikan
# tampilan website SmileOn Lab kepada pengguna.
# Dikerjakan oleh Anggota 1.
# ============================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: smileon-frontend-service:latest
          ports:
            - containerPort: 3000
