# Order-Payment Service - Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: order-payment-service
  labels:
    app: order-payment-service
spec:
  type: NodePort
  selector:
    app: order-payment-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
