apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-auth-pvc
  labels:
    app: mysql-auth
    owner: rakha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
