apiVersion: v1
kind: Service
metadata:
  name: mysql-auth
  labels:
    app: mysql-auth
    owner: rakha
spec:
  type: ClusterIP
  selector:
    app: mysql-auth
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
