apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-recommendation-pvc
  labels:
    app: mysql-recommendation
    owner: roihan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
