apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
    owner: roihan
spec:
  type: NodePort
  selector:
    app: recommendation-service
  ports:
    - port: 3005
      targetPort: 3005
