apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-order-pvc
  labels:
    app: mysql-order
    owner: roihan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
