apiVersion: v1
kind: Service
metadata:
  name: mysql-order
  labels:
    app: mysql-order
    owner: roihan
spec:
  type: ClusterIP
  selector:
    app: mysql-order
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
