apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: portfolio-service
    owner: rakha
spec:
  type: ClusterIP
  selector:
    app: portfolio-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
